In [111]:
import numpy as np
import pandas as pd
df1 = pd.read_excel("C:\\Users\\tanwa\\Downloads\\Final Trend analysis(final renew).xlsx")

In [112]:
df = df1.head(416)
df

,Reviews for Samsung Galaxy Watch,Age,Gender,Location,Occupation,Month,Year,Quarter
0,It's much better than watch ultra 2. Value for...,25-34,M,"Tirunelveli, Tamil Nadu",Working Professional,October,2021,Q4
1,Value for money ? No.\nQuality: built quality ...,35-44,M,"Bengaluru, Karnataka",Working Professional,April,2020,Q2
2,Just one word.......awesome. go for it,18-24,M,"Navi Mumbai, Maharashtra",Student,April,2020,Q2
3,"Android Users other than that of Samsung, you ...",55 and above,M,"New Delhi, Delhi",Retired,September,2020,Q3
4,Exalent watch,55 and above,F,"Devanahalli, Karnataka",Retired,May,2020,Q2
...,...,...,...,...,...,...,...,...
411,Best smartwatch in this time. Many more option...,25-34,F,"Patna, Bihar",Homemaker,March,2024,Q1
412,Not bad,18-24,F,"Kozhikode, Kerala",Working Professional,November,2020,Q4
413,Nice product with lot of features but battery ...,55 and above,F,"Navi Mumbai, Maharashtra",Homemaker,May,2021,Q2
414,Samsung Galaxy Watch 4 Classic LTE: A Comprehe...,25-34,M,"Lucknow, Uttar Pradesh",Freelancer,October,2023,Q4
415,"One of Best Purchase , You Are buying a friend...",55 and above,M,"Bhavnagar, Gujarat",Retired,August,2023,Q3

In [78]:
df2 = df1[418:750]
df2.columns = df1.columns.str.strip()
df2.reset_index(drop=True, inplace=True)
df2.columns = df2.iloc[0]  
df2 = df2[1:].reset_index(drop=True) 
df2

,Reviews for Apple Watch,Age,Gender,Location,Occupation,Month,Year,Quarter
0,The product is a beast ! Feels premium and is ...,25-34,F,"Kalyan, Maharashtra",Homemaker,June,2021,Q2
1,Apple watch Ultra 2 is a beast when it comes t...,55 and above,M,"Kanpur, Uttar Pradesh",Retired,July,2024,Q3
2,Very good product nice Apple Watch thanks flip...,25-34,M,"Chennai, Tamil Nadu",Working Professional,June,2021,Q2
3,Very nice product,35-44,M,"Ahmadnagar, Maharashtra",Working Professional,May,2023,Q2
4,"Nothing to say more , its just a beast in its ...",45-54,F,"West Godavari, Andhra Pradesh",Homemaker,January,2023,Q1
...,...,...,...,...,...,...,...,...
326,I ordered watches for all my family members..\...,35-44,M,"Noida, Uttar Pradesh",Working Professional,October,2024,Q4
327,I ordered watches for all my family members..\...,35-44,M,"Noida, Uttar Pradesh",Working Professional,November,2020,Q4
328,Awesome Watch,55 and above,F,"Ahmedabad, Gujarat",Retired,November,2023,Q4
329,Looks premium and special,25-34,M,"Bengaluru, Karnataka",Working Professional,August,2021,Q3
330,Battery to bad,Under 18,F,"Mumbai, Maharashtra",Student,September,2021,Q3

In [80]:
df3 = df1[752:1305]
df3.columns = df1.columns.str.strip()
df3.reset_index(drop=True, inplace=True)
df3.columns = df3.iloc[0]  
df3 = df3[1:].reset_index(drop=True) 
df3

,Reviews for Noise,Age,Gender,Location,Occupation,Month,Year,Quarter
0,I'm in love with thi product thnks filpkart fo...,25-34,F,"Agra, Uttar Pradesh",Homemaker,September,2023,Q3
1,Loved 😍,45-54,F,"Kolkata, West Bengal",Homemaker,September,2021,Q3
2,VERY NICE 👍 WATCH I'M IMPRESSED 😊 GOOD SERVICE...,55 and above,M,"Mokameh, Bihar",Retired,June,2022,Q2
3,Superb Watch Under This price Range.......\nVa...,45-54,M,"Sultanpur, Uttar Pradesh",Working Professional,July,2024,Q3
4,Nice 👍,Under 18,M,"Kolkata, West Bengal",Student,October,2022,Q4
...,...,...,...,...,...,...,...,...
547,Waste of money,Under 18,F,"Northern Division, Odisha",Student,August,2024,Q3
548,Great experience!!,25-34,F,"Chennai, Tamil Nadu",Homemaker,April,2021,Q2
549,Product was good,25-34,M,"Pune, Maharashtra",Freelancer,February,2024,Q1
550,Good,55 and above,M,"Bengaluru, Karnataka",Freelancer,February,2024,Q1
551,Good morning,25-34,F,"Saharanpur, Uttar Pradesh",Homemaker,March,2021,Q1

In [82]:
df4 = df1[1307:1377]
df4.columns = df1.columns.str.strip()
df4.reset_index(drop=True, inplace=True)
df4.columns = df4.iloc[0]  
df4 = df4[1:].reset_index(drop=True) 
df4

,Reviews for OnePlus Watch,Age,Gender,Location,Occupation,Month,Year,Quarter
0,Good but with flaws\nI have been a samsung wat...,25-34,M,"Chennai, Tamil Nadu",Working Professional,April,2021,Q2
1,Loved it.,18-24,F,"Bengaluru, Karnataka",Working Professional,February,2022,Q1
2,My first smart watch\nWatch was awesome and su...,45-54,M,"Gonikoppal, Karnataka",Working Professional,September,2022,Q3
3,Perfect😍\nBest in Class,35-44,M,"Nellikuppam, Tamil Nadu",Working Professional,December,2024,Q4
4,"In one word...\n\nwe can say,\n\nunbelievable..!!",55 and above,M,"New Delhi, Delhi",Retired,September,2021,Q3
...,...,...,...,...,...,...,...,...
64,Don't,Under 18,M,"Mumbai, Maharashtra",Student,October,2024,Q4
65,I don’t personally use wearable health devices...,18-24,M,"Mumbai, Maharashtra",Student,August,2022,Q3
66,Helpful for tracking steps and quality of sleep,18-24,M,"Mumbai, Maharashtra",Student,September,2020,Q3
67,Well \n\n\n\n,35-44,M,"Aurangabad, Maharashtra",Working Professional,April,2023,Q2
68,It's good.,55 and above,M,"Aurangabad, Maharashtra",Working Professional,March,2020,Q1

In [84]:
df5 = df1[1379:1661]
df5.columns = df1.columns.str.strip()
df5.reset_index(drop=True, inplace=True)
df5.columns = df5.iloc[0]  
df5 = df5[1:].reset_index(drop=True) 
df5

,Reviews for Redmi Watch,Age,Gender,Location,Occupation,Month,Year,Quarter
0,Watch is big in size but looks professional. B...,35-44,F,"Bhubaneswar, Odisha",Homemaker,December,2022,Q4
1,Best smartwatch in this budget with calling an...,45-54,M,"Ghaziabad, Uttar Pradesh",Freelancer,May,2022,Q2
2,The size is too big and it can be slim too. If...,35-44,M,"Madurai, Tamil Nadu",Freelancer,January,2020,Q1
3,Everything is perfect.\nBest of budget smartwa...,18-24,F,"Burdwan, West Bengal",Working Professional,April,2022,Q2
4,Battery back up is superb\nConnectivity is als...,35-44,M,"Gandhinagar, Gujarat",Working Professional,September,2020,Q3
...,...,...,...,...,...,...,...,...
276,Such a wonderful watch!,18-24,F,"Prayagraj, Uttar Pradesh",Working Professional,October,2021,Q4
277,Nc,18-24,M,"Kendrapara, Odisha",Working Professional,July,2020,Q3
278,It is a nice working design with a good lookin...,45-54,F,"Srinagar, Jammu and Kashmir",Homemaker,March,2024,Q1
279,"I use to measure heart beats, distance I walked.",35-44,F,"Mumbai, Maharashtra",Working Professional,February,2020,Q1
280,"good experience , helps to keep somewhat track...",18-24,F,"Mumbai, Maharashtra",Student,March,2024,Q1

In [86]:
df6 = df1[1663:2016]
df6.columns = df1.columns.str.strip()
df6.reset_index(drop=True, inplace=True)
df6.columns = df6.iloc[0]  
df6 = df6[1:].reset_index(drop=True) 
df6

,Reviews for Mi SmartBand,Age,Gender,Location,Occupation,Month,Year,Quarter
0,Good product at this price.,55 and above,M,"Hugli Chinsurah, West Bengal",Retired,June,2021,Q2
1,Best product and it is the original MI Smart B...,25-34,M,"Kottarakkara, Kerala",Working Professional,September,2022,Q3
2,Nice product,45-54,F,"Ranbirsinghpora, Jammu and Kashmir",Homemaker,April,2023,Q2
3,"Really great product I love very much, plzz go...",35-44,F,"Gopeshwar, Uttarakhand",Homemaker,February,2022,Q1
4,Best ...Smooth ...,45-54,M,"Lucknow, Uttar Pradesh",Working Professional,July,2020,Q3
...,...,...,...,...,...,...,...,...
347,awesome product. has a good and soft strap and...,35-44,M,"Eravattur, Kerala",Freelancer,December,2022,Q4
348,amazing something accurate pedometer\nheart ra...,45-54,M,"Chhatarpur, Madhya Pradesh",Working Professional,March,2022,Q1
349,this is the best and excellent work I am happy...,45-54,F,"Mumbai, Maharashtra",Homemaker,March,2022,Q1
350,I was thinking of getting a smart watch for a ...,Under 18,F,"Kolkata, West Bengal",Student,August,2024,Q3
351,Works perfectly! Amazing. Best thing is shows ...,45-54,F,"Bengaluru, Karnataka",Homemaker,December,2021,Q4

In [88]:
df7 = df1[2018:2089]
df7.columns = df1.columns.str.strip()
df7.reset_index(drop=True, inplace=True)
df7.columns = df7.iloc[0]  
df7 = df7[1:].reset_index(drop=True) 
df7

,Reviews for Google Pixel Watch,Age,Gender,Location,Occupation,Month,Year,Quarter
0,I have been using Pixel Watch 2 from the last ...,25-34,M,"Ghaziabad, Uttar Pradesh",Freelancer,September,2024,Q3
1,Yet another overpriced amazing looking unique ...,45-54,F,"Bengaluru, Karnataka",Working Professional,December,2024,Q4
2,The watch looks very stylish and the features ...,Under 18,F,"Miryalaguda, Telangana",Student,March,2020,Q1
3,Cool 😎 watch,45-54,M,"Canacona, Goa",Freelancer,October,2022,Q4
4,The amoled display and overall built are absol...,Under 18,M,"Irinjalakuda, Kerala",Student,January,2021,Q1
...,...,...,...,...,...,...,...,...
65,Perfect,25-34,F,"Patna, Bihar",Homemaker,December,2023,Q4
66,Top Notch!!!!!! ❤️,35-44,F,"Lucknow, Uttar Pradesh",Working Professional,January,2023,Q1
67,"Costly, but totally worth it. The AMOLED displ...",45-54,F,"Mumbai, Maharashtra",Homemaker,June,2021,Q2
68,This is the best watch from Google and is mile...,Under 18,M,"Kolkata, West Bengal",Student,June,2023,Q2
69,Great watch,18-24,M,"Batala, Punjab",Freelancer,August,2020,Q3

In [90]:
df8 = df1[2091:2673]
df8.columns = df1.columns.str.strip()
df8.reset_index(drop=True, inplace=True)
df8.columns = df8.iloc[0]  
df8 = df8[1:].reset_index(drop=True) 
df8

,Reviews for Boat,Age,Gender,Location,Occupation,Month,Year,Quarter
0,Boat smart watch is an impressive wearable dev...,Under 18,F,"Gauri Bazar, Uttar Pradesh",Student,July,2020,Q3
1,Product is very good 😊 love it,35-44,F,"Varanasi, Uttar Pradesh",Homemaker,March,2024,Q1
2,My friend tell about this it was so good produ...,18-24,F,"Madanapalle, Andhra Pradesh",Working Professional,November,2022,Q4
3,U have to charge Daily Or Every 2 Days . . . B...,35-44,M,"Surat, Gujarat",Working Professional,March,2024,Q1
4,Thnkss flipkart..,45-54,F,"Firozabad, Uttar Pradesh",Homemaker,February,2024,Q1
...,...,...,...,...,...,...,...,...
576,Noice,35-44,F,"Teleni Para, West Bengal",Homemaker,October,2020,Q4
577,"Cheating, there is no 100+cloud watch faces on...",55 and above,M,"Latur, Maharashtra",Retired,March,2023,Q1
578,Very nice,18-24,M,"Mumbai, Maharashtra",Freelancer,December,2021,Q4
579,Battery full charge working only 8 hours,Under 18,M,"Ambala, Haryana",Student,September,2023,Q3
580,Bellt size and bellt very bad colety,35-44,M,"Hingoli, Maharashtra",Working Professional,September,2022,Q3

In [92]:
df9 = df1[2675:3368]
df9.columns = df1.columns.str.strip()
df9.reset_index(drop=True, inplace=True)
df9.columns = df9.iloc[0]  
df9 = df9[1:].reset_index(drop=True) 
df9

,Reviews for Fastrack,Age,Gender,Location,Occupation,Month,Year,Quarter
0,Value for money ..thank you Fastrack,25-34,M,"East Godavari, Andhra Pradesh",Working Professional,February,2020,Q1
1,Nice quality,25-34,M,"Agra, Uttar Pradesh",Working Professional,March,2023,Q1
2,Good product,25-34,M,"Kolkata, West Bengal",Freelancer,April,2023,Q2
3,Thank you Flipkart ❣️\nBest Smartwatch for use...,35-44,M,"Purnia, Bihar",Working Professional,September,2022,Q3
4,Nice product,35-44,M,"Jamshedpur, Jharkhand",Working Professional,July,2024,Q3
...,...,...,...,...,...,...,...,...
687,Awesome 👍,45-54,M,"Jabalpur, Madhya Pradesh",Working Professional,January,2021,Q1
688,Product is good I love it,Under 18,F,"Chimakurthy, Andhra Pradesh",Student,November,2024,Q4
689,Good quality thanks for flipkart,45-54,F,"Medchal Malkajgiri District, Telangana",Homemaker,October,2024,Q4
690,Good p,18-24,M,"Berhampur, Odisha",Freelancer,June,2023,Q2
691,This watch is very beautiful,25-34,F,"Azamgarh, Uttar Pradesh",Working Professional,September,2024,Q3

In [94]:
df10 = df1[3370:4284]
df10.columns = df1.columns.str.strip()
df10.reset_index(drop=True, inplace=True)
df10.columns = df10.iloc[0]  
df10 = df10[1:].reset_index(drop=True) 
df10

,Reviews for Fireboltt,Age,Gender,Location,Occupation,Month,Year,Quarter
0,I am using it from a day. It's really good loo...,25-34,M,"Tumkur, Karnataka",Working Professional,November,2024,Q4
1,Nice watch' good deal thnx Flipkart\nI need on...,55 and above,M,"Mumbai, Maharashtra",Retired,May,2023,Q2
2,"Very nice, I have bought for child, he so mush...",25-34,F,"Kanpur, Uttar Pradesh",Homemaker,December,2024,Q4
3,Superb i m impressed,25-34,F,"Chennai, Tamil Nadu",Homemaker,April,2021,Q2
4,Loved it,35-44,M,"New Town, West Bengal",Freelancer,January,2020,Q1
...,...,...,...,...,...,...,...,...
908,We can't call anyone through Bluetooth.But we ...,45-54,F,"Kanjiramkulam, Kerala",Homemaker,August,2020,Q3
909,Good watch,Under 18,M,"Vadodara, Gujarat",Student,August,2022,Q3
910,Very nice ✅✅product,18-24,M,"Ranchi, Jharkhand",Freelancer,April,2023,Q2
911,This to good for the money I paid,Under 18,M,"Bengaluru, Karnataka",Student,June,2021,Q2
912,Best in quality,25-34,M,"Mangalam, Tamil Nadu",Working Professional,April,2020,Q2

In [96]:
df11 = df1[4286:4588]
df11.columns = df1.columns.str.strip()
df11.reset_index(drop=True, inplace=True)
df11.columns = df11.iloc[0]  
df11 = df11[1:].reset_index(drop=True) 
df11

,Reviews for FitBit,Age,Gender,Location,Occupation,Month,Year,Quarter
0,I wasn't a great fan of activity monitors but ...,25-34,F,"Hyderabad, Telangana",Homemaker,May,2022,Q2
1,My wife wanted a smart watch which could guess...,55 and above,M,"Udupi, Karnataka",Retired,July,2023,Q3
2,"Overall the look and the features are good, ho...",35-44,F,"Kolkata, West Bengal",Homemaker,February,2021,Q1
3,Every day I am falling in love with this versa...,25-34,F,"Kanakapura, Karnataka",Homemaker,July,2024,Q3
4,wonderful product,55 and above,M,"Mahindra World City, Tamil Nadu",Student,November,2021,Q4
...,...,...,...,...,...,...,...,...
296,Very good smart watch..,35-44,M,"Dharapuram, Tamil Nadu",Working Professional,November,2022,Q4
297,Great,55 and above,F,"Ludhiana, Punjab",Homemaker,March,2021,Q1
298,Excellent watch..\nWorth to buy,Under 18,F,"Raman, Punjab",Student,July,2022,Q3
299,please don't go for versa 3. The watch softwar...,18-24,F,"Thiruvananthapuram, Kerala",Working Professional,April,2021,Q2
300,Helpful way to keep a track on health everyday,25-34,F,"Aurangabad, Maharashtra",Freelancer,November,2023,Q4

In [98]:
df12 = df1[4590:5289]
df12.columns = df1.columns.str.strip()
df12.reset_index(drop=True, inplace=True)
df12.columns = df12.iloc[0]  
df12 = df12[1:].reset_index(drop=True) 
df12

,Reviews for Boult,Age,Gender,Location,Occupation,Month,Year,Quarter
0,Awesome watch with overloaded features. And it...,25-34,M,"Muzaffarnagar, Uttar Pradesh",Freelancer,January,2022,Q1
1,Good product and best Quality,25-34,M,"Raigarh, Chhattisgarh",Working Professional,August,2021,Q3
2,"Value For Money Product, But Battary Drain Ver...",25-34,M,"Kolhapur, Maharashtra",Working Professional,February,2021,Q1
3,Nice watch very happy 😊,55 and above,F,"Saharsa, Bihar",Homemaker,December,2022,Q4
4,Look wise very good features is decent as othe...,Under 18,F,"Buldhana, Maharashtra",Student,September,2024,Q3
...,...,...,...,...,...,...,...,...
693,Nice 👍,45-54,M,"Janjgir, Chhattisgarh",Working Professional,August,2021,Q3
694,Good product...,35-44,M,"South Twenty Four Parganas District, West Bengal",Working Professional,December,2022,Q4
695,Product is very good 👍😊\nHappy 😊,45-54,M,"Mumbai, Maharashtra",Working Professional,February,2020,Q1
696,Very good,55 and above,F,"Vijalpor, Gujarat",Homemaker,October,2024,Q4
697,Good,35-44,M,"Raigad, Maharashtra",Working Professional,March,2021,Q1

In [100]:
df13 = df1[5291:5886]
df13.columns = df1.columns.str.strip()
df13.reset_index(drop=True, inplace=True)
df13.columns = df13.iloc[0]  
df13 = df13[1:].reset_index(drop=True) 
df13

,Reviews for Amazfit,Age,Gender,Location,Occupation,Month,Year,Quarter
0,It's not a watch but a sophisticated / premium...,18-24,M,"Indore, Madhya Pradesh",Working Professional,May,2021,Q2
1,Just awesome\nDisplay is very nice\nNo lagging...,55 and above,M,"Panihati, West Bengal",Retired,August,2021,Q3
2,Superb watch this watch is amazing\nRealme and...,18-24,M,"East Delhi, Delhi",Working Professional,August,2021,Q3
3,Bestest smartwatch ⌚ ever 😍\nI really liked it...,25-34,M,"Bara Banki, Jharkhand",Freelancer,April,2020,Q2
4,I love this watch ❤️❤️I buy for my sister she ...,25-34,F,"Ullal, Karnataka",Homemaker,July,2022,Q3
...,...,...,...,...,...,...,...,...
589,One of the best smart watch. Top notch quality...,45-54,M,"Hoshiarpur, Punjab",Freelancer,August,2020,Q3
590,"When I bought it my first impression was good,...",55 and above,M,"Dimapur, Nagaland",Retired,February,2022,Q1
591,I liked the product. Straps should be of leath...,35-44,M,"Jammu, Jammu and Kashmir",Working Professional,November,2024,Q4
592,Style and Performance watch.,35-44,F,"Hyderabad, Telangana",Homemaker,September,2023,Q3
593,Loving the classic watch design... most value ...,55 and above,M,"Ziro, Arunachal Pradesh",Retired,August,2022,Q3

In [102]:
df14 = df1[5888:6330]
df14.columns = df1.columns.str.strip()
df14.reset_index(drop=True, inplace=True)
df14.columns = df14.iloc[0]  
df14 = df14[1:].reset_index(drop=True) 
df14

,Reviews for Fossil,Age,Gender,Location,Occupation,Month,Year,Quarter
0,I can say it's a well built good looking watch...,25-34,M,"Hyderabad, Telangana",Working Professional,February,2024,Q1
1,Its a good looking watch with all features tha...,55 and above,M,"New Delhi, Delhi",Retired,May,2021,Q2
2,Pretty decent watch! Good for function & party...,35-44,M,"New Delhi, Delhi",Working Professional,October,2021,Q4
3,i m using this product last 4 months. after re...,25-34,M,"Baleshwar, Gujarat",Working Professional,December,2024,Q4
4,Watch is beautiful and elegant. Run hours is a...,Under 18,M,"Gurugram, Haryana",Student,February,2020,Q1
...,...,...,...,...,...,...,...,...
436,After use of more than 1 year watch is OK... l...,Under 18,M,"Amritsar, Punjab",Student,March,2021,Q1
437,Never ever buy any fossil smart product. Waste...,25-34,F,"Gwalior, Madhya Pradesh",Homemaker,June,2021,Q2
438,Loved the watch,55 and above,M,"Thane, Maharashtra",Retired,November,2020,Q4
439,Overall a great buy but battery is so poor nd ...,55 and above,M,"New Delhi, Delhi",Retired,October,2024,Q4
440,Very bad product,Under 18,M,"Latur, Maharashtra",Student,September,2023,Q3

In [104]:
df.to_csv("df.csv", index=False)
df2.to_csv("df2.csv", index=False)
df3.to_csv("df3.csv", index=False)
df4.to_csv("df4.csv", index=False)
df5.to_csv("df5.csv", index=False)
df6.to_csv("df6.csv", index=False)
df7.to_csv("df7.csv", index=False)
df8.to_csv("df8.csv", index=False)
df9.to_csv("df9.csv", index=False)
df10.to_csv("df10.csv", index=False)
df11.to_csv("df11.csv", index=False)
df12.to_csv("df12.csv", index=False)
df13.to_csv("df13.csv", index=False)
df14.to_csv("df14.csv", index=False)